spring:
  application:
    name: account-service
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bankservice
    username: root
    password: '00000000'
  data:
    redis:
      jedis:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
      port: 6379
      host: 127.0.0.1
othercompanyaccount:
  regist:
    status:
      pending: "PENDING"
      canceled: "CANCELED"
      confirmed: "CONFIRMED"
      rejected: "REJECTED"
  transfer:
    status:
      pending: "PENDING"
      confirmed: "CONFIRMED"
      canceled: "CANCELED"
      rejected: "REJECTED"
server:
  port: 0
bank:
  list:
    kbbank-service:
      ip: 127.0.0.1
    ibkbank-service:
      ip: 127.0.0.1
kafka:
  topic:
    add-other-company-account: "userservice-add-othercompanyaccount"
    update-other-company-account: "userservice-update-othercompanyaccount"
    tranfer-other-company-account: "userservice-tranfer-othercompanyaccount"

account_service:
  exception:
    account_is_empty: "No Account"
    accountHistory_is_empty: "No Account History"
